### ISSUE TITLE
Unable to Make Patches: No module named 'PatchSorter'

### ISSUE THREAD

**Issue by AdroitR** [choosehappy/PatchSorter#3]
After pulling the latest version (5.8) and creating a new docker image (cuda_11), PS is able to upload my files correctly but fails when I click "Make Patches".

The only error I see in the docker logs:

Traceback (most recent call last):
  File "./approaches/make_patches/make_patch_database.py", line 27, in <module>
    from PatchSorter.PS_db import MaskTypeEnum
ModuleNotFoundError: No module named 'PatchSorter'

**Comment by choosehappy** [comment]
Kien, can you please confirm that the proposed solution has worked for you?
I've just merged it in

**Comment by petroslk** [comment]
Hey, This is still an issue. When installing the requirements as shown in the documentation, there is that same import error when trying to make patches.

**Comment by jacksonjacobs1** [comment]
Okay, looks like the following import is the problem:
https://github.com/choosehappy/PatchSorter/blob/1e5f7c1911e9f6f77dfb9c05159289c9d6bbdc86/approaches/make_patches/make_patch_database.py#L27

I haven't had the chance to confirm yet, but this is probably just a misuse of intra-project imports:
https://fadil-nohur.medium.com/resolving-intra-project-imports-in-python-a-simple-guide-872775f64277

i.e, that import statement would work if PatchSorter was included in python's sys.path variable.

@AdroitR fixed this problem for the docker installation in #4 , by explicitly setting the python path environment variable within the dockerfile:
https://github.com/choosehappy/PatchSorter/blob/1e5f7c1911e9f6f77dfb9c05159289c9d6bbdc86/cuda_11/Dockerfile#L3

However, a more general solution would be to set the project path within python itself: `sys.path.append('/path/to/PatchSorter')`

@choosehappy thoughts?

**Comment by choosehappy** [comment]
> However, a more general solution would be to set the project path within python itself: sys.path.append('/path/to/PatchSorter')

this seems kind of janky, doesn't it? I've not seen this approach taken in any other python projects - is this industry standard?

shouldn't the imports be resolved "correctly"?

**Comment by petroslk** [comment]
I think the best way forward would definitely be to structure the project with subdirectories and __init__ files in each, have a proper setup.py installation to be sure that function imports work.

**Comment by jacksonjacobs1** [comment]
Agree with petros. I think this fits in with making patchsorter a pip installable package.

**Comment by choosehappy** [comment]
agree - and more so, repacking to match histoqc packaging has been on the list for a long time, which would as well address this


one question i had...I've used PS previously, as have others, without this error occurring -- whats changed?

**Comment by jacksonjacobs1** [comment]
I'm stumped as well. 

Would like to point out that #18 by Nan packages PatchSorter in a format which follows HistoQC. I reviewed the PR and it looked good to me. 

@choosehappy Can you take a look and confirm whether the PR is ready to merge in?

**Comment by choosehappy** [comment]
it looks nice to me -- the question is -- did someone test to make sure it actually works all the way through? lots of code changes here!

**Comment by jacksonjacobs1** [comment]
Nan commented that he tested the repackaged version on his local instance using the example images.

@nanli-emory how extensive were your tests of the repackaged version? Did you test e.g, labeling, training, and plot interaction?

**Comment by nanli-emory** [comment]
> Nan commented that he tested the repackaged version on his local instance using the example images.
> 
> @nanli-emory how extensive were your tests of the repackaged version? Did you test e.g, labeling, training, and plot interaction?

Hi @choosehappy & @jacksonjacobs1,

I tested the interaction that I can find on my local instance with the example images. Do you have any suggestions on how we can do a better test for PatchSorter?
